<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>WinterRose.Preferences</Title>
    <Version>26.3.0</Version>
    <Authors>TheSnowOwl</Authors>
    <Company>WinterRose</Company>
    <Description>A library to aid in the usage of user preferences</Description>
    <Copyright>WinterRose</Copyright>
    <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\WinterRose.WinterForge\WinterRose.WinterForge.Abstractions\WinterRose.WinterForge.Abstractions.csproj" />
  </ItemGroup>

</Project>
