<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>WinterRose.Preferences.Storage</Title>
    <Version>26.3.0</Version>
    <Authors>TheSnowOwl</Authors>
    <Company>WinterRose</Company>
    <Copyright>WinterRose</Copyright>
    <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinterRose.UserPreferences\WinterRose.Preferences.csproj" />
  </ItemGroup>

</Project>
